version: '5.1'

services:
  news-service:
    build:
      context: ./news-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - newsapi.key=ccaf5d41cc5140c984818c344edcc14d
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - news-service
    restart: unless-stopped